version: '3.8'

services:
  web:
    build: .
    expose:
      - "5000"
    volumes:
      - .:/app
    command: python app.py
    networks:
      - app_network
      - steve-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    depends_on:
      - web
    networks:
      - app_network
      - steve-network

networks:
  app_network:
    driver: bridge
  steve-network: 
    external:
      name: steve-steve-360_default
