version: '3.8'

services:
  backend:
    build: .
    expose:
      - "5000"
    volumes:
      - .:/app
    command: flask run
    networks:
      - app_network
      - steve-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
  steve-network: 
    external:
      name: ${DOCKER_NETWORK_NAME}
